"""
ModelRegistry — Centralized catalog of all supported ML models with metadata.
"""

MODEL_REGISTRY = {
    # ── REGRESSION ──────────────────────────────────────────────────────────
    "linear_regression": {
        "name": "Linear Regression",
        "task": "regression",
        "module": "sklearn.linear_model",
        "class": "LinearRegression",
        "params": {},
        "pros": ["Interpretable", "Fast", "No hyperparameters"],
        "cons": ["Assumes linearity", "Sensitive to outliers"],
        "complexity": "low",
        "interpretability": "high",
        "use_when": "Features have linear relationship with target",
    },
    "ridge": {
        "name": "Ridge Regression",
        "task": "regression",
        "module": "sklearn.linear_model",
        "class": "Ridge",
        "params": {"alpha": 1.0},
        "pros": ["Handles multicollinearity", "Regularized"],
        "cons": ["Assumes linearity"],
        "complexity": "low",
        "interpretability": "high",
        "use_when": "Many correlated features",
    },
    "random_forest_reg": {
        "name": "Random Forest Regressor",
        "task": "regression",
        "module": "sklearn.ensemble",
        "class": "RandomForestRegressor",
        "params": {"n_estimators": 100, "random_state": 42, "n_jobs": -1},
        "pros": ["Non-linear", "Feature importance", "Robust"],
        "cons": ["Less interpretable", "Memory-heavy"],
        "complexity": "medium",
        "interpretability": "medium",
        "use_when": "Non-linear patterns, mixed feature types",
    },
    "gradient_boosting_reg": {
        "name": "Gradient Boosting Regressor",
        "task": "regression",
        "module": "sklearn.ensemble",
        "class": "GradientBoostingRegressor",
        "params": {"n_estimators": 100, "learning_rate": 0.1, "random_state": 42},
        "pros": ["High accuracy", "Handles non-linearity"],
        "cons": ["Slower training", "Needs tuning"],
        "complexity": "high",
        "interpretability": "medium",
        "use_when": "Best accuracy needed on tabular data",
    },
    "xgboost_reg": {
        "name": "XGBoost Regressor",
        "task": "regression",
        "module": "xgboost",
        "class": "XGBRegressor",
        "params": {"n_estimators": 100, "learning_rate": 0.1, "random_state": 42, "verbosity": 0},
        "pros": ["State-of-the-art", "Handles missing values", "Fast"],
        "cons": ["Black-box", "Many hyperparameters"],
        "complexity": "high",
        "interpretability": "medium",
        "use_when": "Competition-level accuracy on structured data",
    },
    "svr": {
        "name": "Support Vector Regressor",
        "task": "regression",
        "module": "sklearn.svm",
        "class": "SVR",
        "params": {"kernel": "rbf", "C": 1.0},
        "pros": ["Works in high dimensions", "Robust to outliers"],
        "cons": ["Slow on large data", "Needs scaling"],
        "complexity": "medium",
        "interpretability": "low",
        "use_when": "Small/medium datasets, non-linear patterns",
    },

    # ── CLASSIFICATION ───────────────────────────────────────────────────────
    "logistic_regression": {
        "name": "Logistic Regression",
        "task": "classification",
        "module": "sklearn.linear_model",
        "class": "LogisticRegression",
        "params": {"max_iter": 1000, "random_state": 42},
        "pros": ["Interpretable", "Fast", "Probability outputs"],
        "cons": ["Assumes linearity", "Poor on complex boundaries"],
        "complexity": "low",
        "interpretability": "high",
        "use_when": "Baseline, interpretable model needed",
    },
    "random_forest_clf": {
        "name": "Random Forest Classifier",
        "task": "classification",
        "module": "sklearn.ensemble",
        "class": "RandomForestClassifier",
        "params": {"n_estimators": 100, "random_state": 42, "n_jobs": -1},
        "pros": ["Robust", "Feature importance", "No scaling needed"],
        "cons": ["Memory-heavy", "Slow prediction at scale"],
        "complexity": "medium",
        "interpretability": "medium",
        "use_when": "General-purpose, feature selection needed",
    },
    "gradient_boosting_clf": {
        "name": "Gradient Boosting Classifier",
        "task": "classification",
        "module": "sklearn.ensemble",
        "class": "GradientBoostingClassifier",
        "params": {"n_estimators": 100, "learning_rate": 0.1, "random_state": 42},
        "pros": ["High accuracy", "Handles imbalance"],
        "cons": ["Training time", "Overfitting risk"],
        "complexity": "high",
        "interpretability": "medium",
        "use_when": "High accuracy needed",
    },
    "xgboost_clf": {
        "name": "XGBoost Classifier",
        "task": "classification",
        "module": "xgboost",
        "class": "XGBClassifier",
        "params": {"n_estimators": 100, "learning_rate": 0.1, "random_state": 42, "verbosity": 0, "eval_metric": "logloss"},
        "pros": ["Industry-standard", "Fast", "Handles missing values"],
        "cons": ["Needs tuning", "Less interpretable"],
        "complexity": "high",
        "interpretability": "medium",
        "use_when": "Best classifier for tabular data",
    },
    "svm_clf": {
        "name": "Support Vector Classifier",
        "task": "classification",
        "module": "sklearn.svm",
        "class": "SVC",
        "params": {"kernel": "rbf", "probability": True, "random_state": 42},
        "pros": ["High-dimensional data", "Kernel trick"],
        "cons": ["Slow on large data", "Needs scaling"],
        "complexity": "medium",
        "interpretability": "low",
        "use_when": "Text/image data, medium-sized datasets",
    },
    "decision_tree": {
        "name": "Decision Tree",
        "task": "classification",
        "module": "sklearn.tree",
        "class": "DecisionTreeClassifier",
        "params": {"max_depth": 10, "random_state": 42},
        "pros": ["Fully interpretable", "No scaling needed", "Visual"],
        "cons": ["Overfits easily", "Unstable"],
        "complexity": "low",
        "interpretability": "very_high",
        "use_when": "Explainability is critical",
    },

    # ── CLUSTERING ───────────────────────────────────────────────────────────
    "kmeans": {
        "name": "K-Means Clustering",
        "task": "clustering",
        "module": "sklearn.cluster",
        "class": "KMeans",
        "params": {"n_clusters": 3, "random_state": 42, "n_init": "auto"},
        "pros": ["Fast", "Scalable", "Simple"],
        "cons": ["Assumes spherical clusters", "Needs k upfront"],
        "complexity": "low",
        "interpretability": "high",
        "use_when": "Known approximate number of clusters, large data",
    },
    "dbscan": {
        "name": "DBSCAN",
        "task": "clustering",
        "module": "sklearn.cluster",
        "class": "DBSCAN",
        "params": {"eps": 0.5, "min_samples": 5},
        "pros": ["Finds arbitrary shapes", "Detects outliers", "No k needed"],
        "cons": ["Sensitive to eps/min_samples", "Slow on large data"],
        "complexity": "medium",
        "interpretability": "medium",
        "use_when": "Unknown cluster count, irregular shapes",
    },
    "agglomerative": {
        "name": "Agglomerative Clustering",
        "task": "clustering",
        "module": "sklearn.cluster",
        "class": "AgglomerativeClustering",
        "params": {"n_clusters": 3, "linkage": "ward"},
        "pros": ["Hierarchical structure", "No random init"],
        "cons": ["O(n²) memory", "Slow on large data"],
        "complexity": "medium",
        "interpretability": "medium",
        "use_when": "Hierarchical structure needed, small/medium data",
    },

    # ── TIME SERIES ──────────────────────────────────────────────────────────
    "arima": {
        "name": "ARIMA",
        "task": "time_series",
        "module": "statsmodels.tsa.arima.model",
        "class": "ARIMA",
        "params": {"order": (1, 1, 1)},
        "pros": ["Statistical rigor", "Interpretable", "Confidence intervals"],
        "cons": ["Requires stationarity", "Manual order selection"],
        "complexity": "medium",
        "interpretability": "high",
        "use_when": "Univariate time series, short horizon forecasting",
    },
    "exponential_smoothing": {
        "name": "Exponential Smoothing (Holt-Winters)",
        "task": "time_series",
        "module": "statsmodels.tsa.holtwinters",
        "class": "ExponentialSmoothing",
        "params": {"trend": "add", "seasonal": "add", "seasonal_periods": 12},
        "pros": ["Handles trend & seasonality", "Fast"],
        "cons": ["Linear assumptions"],
        "complexity": "low",
        "interpretability": "high",
        "use_when": "Seasonal data, demand forecasting",
    },
    "random_forest_ts": {
        "name": "Random Forest (Time Series)",
        "task": "time_series",
        "module": "sklearn.ensemble",
        "class": "RandomForestRegressor",
        "params": {"n_estimators": 100, "random_state": 42},
        "pros": ["Captures non-linear patterns", "Feature-rich"],
        "cons": ["Does not extrapolate"],
        "complexity": "medium",
        "interpretability": "medium",
        "use_when": "Non-linear time series with many features",
    },
}
